// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUV7ZbGcsQfQw-pMJ8aDuvvx2mNHVcSuk',
    appId: '1:757118032566:web:60babf63093bb83c01a417',
    messagingSenderId: '757118032566',
    projectId: 'chatflutter-c7e0b',
    authDomain: 'chatflutter-c7e0b.firebaseapp.com',
    databaseURL: 'https://chatflutter-c7e0b-default-rtdb.firebaseio.com',
    storageBucket: 'chatflutter-c7e0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMdKjlZIX4g7j0VtE2nC9z8ds6QgStYyw',
    appId: '1:757118032566:android:e33e833f64c6caae01a417',
    messagingSenderId: '757118032566',
    projectId: 'chatflutter-c7e0b',
    databaseURL: 'https://chatflutter-c7e0b-default-rtdb.firebaseio.com',
    storageBucket: 'chatflutter-c7e0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsoKJtWtY0oF0xGGb-S6LTSWNvQ3LbhgM',
    appId: '1:757118032566:ios:57a938641dcaad6c01a417',
    messagingSenderId: '757118032566',
    projectId: 'chatflutter-c7e0b',
    databaseURL: 'https://chatflutter-c7e0b-default-rtdb.firebaseio.com',
    storageBucket: 'chatflutter-c7e0b.appspot.com',
    androidClientId: '757118032566-5dnasoj889jr9vckopdvsha8kutndlr7.apps.googleusercontent.com',
    iosClientId: '757118032566-gqjnqhcl5mvopv7uthsf0s44ifdgf1o9.apps.googleusercontent.com',
    iosBundleId: 'br.com.gobi.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsoKJtWtY0oF0xGGb-S6LTSWNvQ3LbhgM',
    appId: '1:757118032566:ios:57a938641dcaad6c01a417',
    messagingSenderId: '757118032566',
    projectId: 'chatflutter-c7e0b',
    databaseURL: 'https://chatflutter-c7e0b-default-rtdb.firebaseio.com',
    storageBucket: 'chatflutter-c7e0b.appspot.com',
    androidClientId: '757118032566-5dnasoj889jr9vckopdvsha8kutndlr7.apps.googleusercontent.com',
    iosClientId: '757118032566-gqjnqhcl5mvopv7uthsf0s44ifdgf1o9.apps.googleusercontent.com',
    iosBundleId: 'br.com.gobi.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUV7ZbGcsQfQw-pMJ8aDuvvx2mNHVcSuk',
    appId: '1:757118032566:web:85993e726ed122ab01a417',
    messagingSenderId: '757118032566',
    projectId: 'chatflutter-c7e0b',
    authDomain: 'chatflutter-c7e0b.firebaseapp.com',
    databaseURL: 'https://chatflutter-c7e0b-default-rtdb.firebaseio.com',
    storageBucket: 'chatflutter-c7e0b.appspot.com',
  );
}
